### ISSUE TITLE
Issue with Checkbox for settings

### ISSUE THREAD

**Issue by LRTNZ** [acoollevel/uoa-mediaplayer-plus#43]
https://github.com/acoollevel/uoa-mediaplayer-plus/blob/49fe61a0ee53c8192c50de9729ed2a9ee510e6e3/popup/popup.js#L51

Due to this line, we can not use a checkbox for any other settings in the popup. I can see the value in being able to do this, however a way where it can be done without interferring with the functionality for all settings would be preferrable.
Could you please do it through the use of something like this: https://www.geeksforgeeks.org/how-to-call-function-from-it-name-stored-in-a-string-using-javascript/
And just add a custom argument/parameter to the checkbox tag, that is maybe "funcToCall='nameOfFunction'"

**Comment by acoollevel** [comment]
We absolutely can use the checkbox for other settings
